//
// Copyright (c) 2025 [Limark Dcunha]
// All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: message/message.proto

// Use this command
// export PATH="$PATH:$(go env GOPATH)/bin"
// protoc --go_out=. --go_opt=paths=source_relative        --go-grpc_out=. --go-grpc_opt=paths=source_relative     message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcceptType int32

const (
	AcceptType_INTRA_SHARD AcceptType = 0
	AcceptType_PREPARE     AcceptType = 1
	AcceptType_ABORT       AcceptType = 2
	AcceptType_COMMIT      AcceptType = 3
)

// Enum value maps for AcceptType.
var (
	AcceptType_name = map[int32]string{
		0: "INTRA_SHARD",
		1: "PREPARE",
		2: "ABORT",
		3: "COMMIT",
	}
	AcceptType_value = map[string]int32{
		"INTRA_SHARD": 0,
		"PREPARE":     1,
		"ABORT":       2,
		"COMMIT":      3,
	}
)

func (x AcceptType) Enum() *AcceptType {
	p := new(AcceptType)
	*p = x
	return p
}

func (x AcceptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcceptType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_message_proto_enumTypes[0].Descriptor()
}

func (AcceptType) Type() protoreflect.EnumType {
	return &file_message_message_proto_enumTypes[0]
}

func (x AcceptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcceptType.Descriptor instead.
func (AcceptType) EnumDescriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	ClientId      int32                  `protobuf:"varint,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	RoundNumber   int32                  `protobuf:"varint,2,opt,name=RoundNumber,proto3" json:"RoundNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *BallotNumber) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BallotNumber) GetRoundNumber() int32 {
	if x != nil {
		return x.RoundNumber
	}
	return 0
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	AcceptType    AcceptType             `protobuf:"varint,4,opt,name=AcceptType,proto3,enum=message.AcceptType" json:"AcceptType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AcceptMessage) GetAcceptType() AcceptType {
	if x != nil {
		return x.AcceptType
	}
	return AcceptType_INTRA_SHARD
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,4,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	AcceptType    AcceptType             `protobuf:"varint,5,opt,name=AcceptType,proto3,enum=message.AcceptType" json:"AcceptType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptedMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptedMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptedMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AcceptedMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *AcceptedMessage) GetAcceptType() AcceptType {
	if x != nil {
		return x.AcceptType
	}
	return AcceptType_INTRA_SHARD
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	AcceptType    AcceptType             `protobuf:"varint,4,opt,name=AcceptType,proto3,enum=message.AcceptType" json:"AcceptType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *CommitMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *CommitMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CommitMessage) GetAcceptType() AcceptType {
	if x != nil {
		return x.AcceptType
	}
	return AcceptType_INTRA_SHARD
}

type ReplyMessage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ballot                 *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	ClientRequestTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ClientRequestTimestamp,proto3" json:"ClientRequestTimestamp,omitempty"`
	Status                 string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	ClientId               int32                  `protobuf:"varint,4,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *ReplyMessage) GetClientRequestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientRequestTimestamp
	}
	return nil
}

func (x *ReplyMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ReplyMessage) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type PrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrepareMessage) Reset() {
	*x = PrepareMessage{}
	mi := &file_message_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrepareMessage) ProtoMessage() {}

func (x *PrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrepareMessage.ProtoReflect.Descriptor instead.
func (*PrepareMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{7}
}

func (x *PrepareMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

type PromiseMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ballot               *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	AcceptLog            []*AcceptedMessage     `protobuf:"bytes,2,rep,name=AcceptLog,proto3" json:"AcceptLog,omitempty"`
	NodeId               int32                  `protobuf:"varint,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	LastCheckpointSeq    int32                  `protobuf:"varint,4,opt,name=LastCheckpointSeq,proto3" json:"LastCheckpointSeq,omitempty"`
	LastCheckpointDigest string                 `protobuf:"bytes,5,opt,name=LastCheckpointDigest,proto3" json:"LastCheckpointDigest,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PromiseMessage) Reset() {
	*x = PromiseMessage{}
	mi := &file_message_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromiseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromiseMessage) ProtoMessage() {}

func (x *PromiseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromiseMessage.ProtoReflect.Descriptor instead.
func (*PromiseMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{8}
}

func (x *PromiseMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *PromiseMessage) GetAcceptLog() []*AcceptedMessage {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

func (x *PromiseMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PromiseMessage) GetLastCheckpointSeq() int32 {
	if x != nil {
		return x.LastCheckpointSeq
	}
	return 0
}

func (x *PromiseMessage) GetLastCheckpointDigest() string {
	if x != nil {
		return x.LastCheckpointDigest
	}
	return ""
}

type NewViewMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ballot               *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	AcceptLog            []*AcceptedMessage     `protobuf:"bytes,2,rep,name=AcceptLog,proto3" json:"AcceptLog,omitempty"`
	NodeId               int32                  `protobuf:"varint,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	MinSeq               int32                  `protobuf:"varint,4,opt,name=MinSeq,proto3" json:"MinSeq,omitempty"`
	MaxSeq               int32                  `protobuf:"varint,5,opt,name=MaxSeq,proto3" json:"MaxSeq,omitempty"`
	LastCheckpointDigest string                 `protobuf:"bytes,6,opt,name=LastCheckpointDigest,proto3" json:"LastCheckpointDigest,omitempty"`
	MinSeqNodeId         int32                  `protobuf:"varint,7,opt,name=MinSeqNodeId,proto3" json:"MinSeqNodeId,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NewViewMessage) Reset() {
	*x = NewViewMessage{}
	mi := &file_message_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewViewMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewViewMessage) ProtoMessage() {}

func (x *NewViewMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewViewMessage.ProtoReflect.Descriptor instead.
func (*NewViewMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{9}
}

func (x *NewViewMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *NewViewMessage) GetAcceptLog() []*AcceptedMessage {
	if x != nil {
		return x.AcceptLog
	}
	return nil
}

func (x *NewViewMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *NewViewMessage) GetMinSeq() int32 {
	if x != nil {
		return x.MinSeq
	}
	return 0
}

func (x *NewViewMessage) GetMaxSeq() int32 {
	if x != nil {
		return x.MaxSeq
	}
	return 0
}

func (x *NewViewMessage) GetLastCheckpointDigest() string {
	if x != nil {
		return x.LastCheckpointDigest
	}
	return ""
}

func (x *NewViewMessage) GetMinSeqNodeId() int32 {
	if x != nil {
		return x.MinSeqNodeId
	}
	return 0
}

type CheckpointMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SequenceNum   int32                  `protobuf:"varint,1,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Digest        string                 `protobuf:"bytes,2,opt,name=Digest,proto3" json:"Digest,omitempty"`
	NodeId        int32                  `protobuf:"varint,3,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointMessage) Reset() {
	*x = CheckpointMessage{}
	mi := &file_message_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointMessage) ProtoMessage() {}

func (x *CheckpointMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointMessage.ProtoReflect.Descriptor instead.
func (*CheckpointMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{10}
}

func (x *CheckpointMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CheckpointMessage) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *CheckpointMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type StateTranserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	TargetSeq     int32                  `protobuf:"varint,2,opt,name=TargetSeq,proto3" json:"TargetSeq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateTranserRequest) Reset() {
	*x = StateTranserRequest{}
	mi := &file_message_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTranserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTranserRequest) ProtoMessage() {}

func (x *StateTranserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTranserRequest.ProtoReflect.Descriptor instead.
func (*StateTranserRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{11}
}

func (x *StateTranserRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StateTranserRequest) GetTargetSeq() int32 {
	if x != nil {
		return x.TargetSeq
	}
	return 0
}

type StateTransferResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LatestCheckpointSeqNum int32                  `protobuf:"varint,1,opt,name=LatestCheckpointSeqNum,proto3" json:"LatestCheckpointSeqNum,omitempty"`
	State                  map[string]int32       `protobuf:"bytes,2,rep,name=State,proto3" json:"State,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *StateTransferResponse) Reset() {
	*x = StateTransferResponse{}
	mi := &file_message_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransferResponse) ProtoMessage() {}

func (x *StateTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransferResponse.ProtoReflect.Descriptor instead.
func (*StateTransferResponse) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{12}
}

func (x *StateTransferResponse) GetLatestCheckpointSeqNum() int32 {
	if x != nil {
		return x.LatestCheckpointSeqNum
	}
	return 0
}

func (x *StateTransferResponse) GetState() map[string]int32 {
	if x != nil {
		return x.State
	}
	return nil
}

type TwoPCPrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ClientRequest         `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCPrepareMessage) Reset() {
	*x = TwoPCPrepareMessage{}
	mi := &file_message_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCPrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCPrepareMessage) ProtoMessage() {}

func (x *TwoPCPrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCPrepareMessage.ProtoReflect.Descriptor instead.
func (*TwoPCPrepareMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{13}
}

func (x *TwoPCPrepareMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TwoPCPrepareMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type TwoPCPreparedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ClientRequest         `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCPreparedMessage) Reset() {
	*x = TwoPCPreparedMessage{}
	mi := &file_message_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCPreparedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCPreparedMessage) ProtoMessage() {}

func (x *TwoPCPreparedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCPreparedMessage.ProtoReflect.Descriptor instead.
func (*TwoPCPreparedMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{14}
}

func (x *TwoPCPreparedMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TwoPCPreparedMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type TwoPCAbortMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ClientRequest         `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCAbortMessage) Reset() {
	*x = TwoPCAbortMessage{}
	mi := &file_message_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCAbortMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCAbortMessage) ProtoMessage() {}

func (x *TwoPCAbortMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCAbortMessage.ProtoReflect.Descriptor instead.
func (*TwoPCAbortMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{15}
}

func (x *TwoPCAbortMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TwoPCAbortMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type TwoPCCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ClientRequest         `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCCommitMessage) Reset() {
	*x = TwoPCCommitMessage{}
	mi := &file_message_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCCommitMessage) ProtoMessage() {}

func (x *TwoPCCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCCommitMessage.ProtoReflect.Descriptor instead.
func (*TwoPCCommitMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{16}
}

func (x *TwoPCCommitMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TwoPCCommitMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type TwoPCAckMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *ClientRequest         `protobuf:"bytes,1,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	AckType       string                 `protobuf:"bytes,3,opt,name=AckType,proto3" json:"AckType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TwoPCAckMessage) Reset() {
	*x = TwoPCAckMessage{}
	mi := &file_message_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwoPCAckMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwoPCAckMessage) ProtoMessage() {}

func (x *TwoPCAckMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwoPCAckMessage.ProtoReflect.Descriptor instead.
func (*TwoPCAckMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{17}
}

func (x *TwoPCAckMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *TwoPCAckMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *TwoPCAckMessage) GetAckType() string {
	if x != nil {
		return x.AckType
	}
	return ""
}

type PrintBalanceReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datapoint     string                 `protobuf:"bytes,1,opt,name=Datapoint,proto3" json:"Datapoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrintBalanceReq) Reset() {
	*x = PrintBalanceReq{}
	mi := &file_message_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrintBalanceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrintBalanceReq) ProtoMessage() {}

func (x *PrintBalanceReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrintBalanceReq.ProtoReflect.Descriptor instead.
func (*PrintBalanceReq) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{18}
}

func (x *PrintBalanceReq) GetDatapoint() string {
	if x != nil {
		return x.Datapoint
	}
	return ""
}

var File_message_message_proto protoreflect.FileDescriptor

const file_message_message_proto_rawDesc = "" +
	"\n" +
	"\x15message/message.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06Sender\x18\x01 \x01(\tR\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x02 \x01(\tR\bReceiver\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\"\x9d\x01\n" +
	"\rClientRequest\x128\n" +
	"\tTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x126\n" +
	"\vTransaction\x18\x02 \x01(\v2\x14.message.TransactionR\vTransaction\x12\x1a\n" +
	"\bClientId\x18\x03 \x01(\x05R\bClientId\"H\n" +
	"\fBallotNumber\x12\x16\n" +
	"\x06NodeId\x18\x01 \x01(\x05R\x06NodeId\x12 \n" +
	"\vRoundNumber\x18\x02 \x01(\x05R\vRoundNumber\"\xc7\x01\n" +
	"\rAcceptMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\x123\n" +
	"\n" +
	"AcceptType\x18\x04 \x01(\x0e2\x13.message.AcceptTypeR\n" +
	"AcceptType\"\xe1\x01\n" +
	"\x0fAcceptedMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x04 \x01(\x05R\x06NodeId\x123\n" +
	"\n" +
	"AcceptType\x18\x05 \x01(\x0e2\x13.message.AcceptTypeR\n" +
	"AcceptType\"\xc7\x01\n" +
	"\rCommitMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\x123\n" +
	"\n" +
	"AcceptType\x18\x04 \x01(\x0e2\x13.message.AcceptTypeR\n" +
	"AcceptType\"\xc5\x01\n" +
	"\fReplyMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12R\n" +
	"\x16ClientRequestTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x16ClientRequestTimestamp\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status\x12\x1a\n" +
	"\bClientId\x18\x04 \x01(\x05R\bClientId\"?\n" +
	"\x0ePrepareMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\"\xf1\x01\n" +
	"\x0ePromiseMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x126\n" +
	"\tAcceptLog\x18\x02 \x03(\v2\x18.message.AcceptedMessageR\tAcceptLog\x12\x16\n" +
	"\x06NodeId\x18\x03 \x01(\x05R\x06NodeId\x12,\n" +
	"\x11LastCheckpointSeq\x18\x04 \x01(\x05R\x11LastCheckpointSeq\x122\n" +
	"\x14LastCheckpointDigest\x18\x05 \x01(\tR\x14LastCheckpointDigest\"\x97\x02\n" +
	"\x0eNewViewMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x126\n" +
	"\tAcceptLog\x18\x02 \x03(\v2\x18.message.AcceptedMessageR\tAcceptLog\x12\x16\n" +
	"\x06NodeId\x18\x03 \x01(\x05R\x06NodeId\x12\x16\n" +
	"\x06MinSeq\x18\x04 \x01(\x05R\x06MinSeq\x12\x16\n" +
	"\x06MaxSeq\x18\x05 \x01(\x05R\x06MaxSeq\x122\n" +
	"\x14LastCheckpointDigest\x18\x06 \x01(\tR\x14LastCheckpointDigest\x12\"\n" +
	"\fMinSeqNodeId\x18\a \x01(\x05R\fMinSeqNodeId\"e\n" +
	"\x11CheckpointMessage\x12 \n" +
	"\vSequenceNum\x18\x01 \x01(\x05R\vSequenceNum\x12\x16\n" +
	"\x06Digest\x18\x02 \x01(\tR\x06Digest\x12\x16\n" +
	"\x06NodeId\x18\x03 \x01(\x05R\x06NodeId\"K\n" +
	"\x13StateTranserRequest\x12\x16\n" +
	"\x06NodeId\x18\x01 \x01(\x05R\x06NodeId\x12\x1c\n" +
	"\tTargetSeq\x18\x02 \x01(\x05R\tTargetSeq\"\xca\x01\n" +
	"\x15StateTransferResponse\x126\n" +
	"\x16LatestCheckpointSeqNum\x18\x01 \x01(\x05R\x16LatestCheckpointSeqNum\x12?\n" +
	"\x05State\x18\x02 \x03(\v2).message.StateTransferResponse.StateEntryR\x05State\x1a8\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"_\n" +
	"\x13TwoPCPrepareMessage\x120\n" +
	"\aRequest\x18\x01 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x05R\x06NodeId\"`\n" +
	"\x14TwoPCPreparedMessage\x120\n" +
	"\aRequest\x18\x01 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x05R\x06NodeId\"]\n" +
	"\x11TwoPCAbortMessage\x120\n" +
	"\aRequest\x18\x01 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x05R\x06NodeId\"^\n" +
	"\x12TwoPCCommitMessage\x120\n" +
	"\aRequest\x18\x01 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x05R\x06NodeId\"u\n" +
	"\x0fTwoPCAckMessage\x120\n" +
	"\aRequest\x18\x01 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x02 \x01(\x05R\x06NodeId\x12\x18\n" +
	"\aAckType\x18\x03 \x01(\tR\aAckType\"/\n" +
	"\x0fPrintBalanceReq\x12\x1c\n" +
	"\tDatapoint\x18\x01 \x01(\tR\tDatapoint*A\n" +
	"\n" +
	"AcceptType\x12\x0f\n" +
	"\vINTRA_SHARD\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\t\n" +
	"\x05ABORT\x10\x02\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x032\xcd\n" +
	"\n" +
	"\x0eMessageService\x12D\n" +
	"\x12SendRequestMessage\x12\x16.message.ClientRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fHandleAccept\x12\x16.message.AcceptMessage\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eHandleAccepted\x12\x18.message.AcceptedMessage\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fHandleCommit\x12\x16.message.CommitMessage\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rHandlePrepare\x12\x17.message.PrepareMessage\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rHandlePromise\x12\x17.message.PromiseMessage\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rHandleNewView\x12\x17.message.NewViewMessage\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\x10HandleCheckpoint\x12\x1a.message.CheckpointMessage\x1a\x16.google.protobuf.Empty\x12P\n" +
	"\x18MakeStateTransferRequest\x12\x1c.message.StateTranserRequest\x1a\x16.google.protobuf.Empty\x12U\n" +
	"\x1bHandleStateTransferResponse\x12\x1e.message.StateTransferResponse\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x12HandleTwoPCPrepare\x12\x1c.message.TwoPCPrepareMessage\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x13HandleTwoPCPrepared\x12\x1d.message.TwoPCPreparedMessage\x1a\x16.google.protobuf.Empty\x12S\n" +
	"\x1dHandleTwoPCAbortAsCoordinator\x12\x1a.message.TwoPCAbortMessage\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x11HandleTwoPCCommit\x12\x1b.message.TwoPCCommitMessage\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eHandleTwoPCAck\x12\x18.message.TwoPCAckMessage\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\x0ePrintAcceptLog\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12:\n" +
	"\bFailNode\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n" +
	"\vRecoverNode\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\fPrintBalance\x12\x18.message.PrintBalanceReq\x1a\x16.google.protobuf.Empty2M\n" +
	"\rClientService\x12<\n" +
	"\vHandleReply\x12\x15.message.ReplyMessage\x1a\x16.google.protobuf.EmptyB\x1fZ\x1dtransaction-processor/messageb\x06proto3"

var (
	file_message_message_proto_rawDescOnce sync.Once
	file_message_message_proto_rawDescData []byte
)

func file_message_message_proto_rawDescGZIP() []byte {
	file_message_message_proto_rawDescOnce.Do(func() {
		file_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)))
	})
	return file_message_message_proto_rawDescData
}

var file_message_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_message_message_proto_goTypes = []any{
	(AcceptType)(0),               // 0: message.AcceptType
	(*Transaction)(nil),           // 1: message.Transaction
	(*ClientRequest)(nil),         // 2: message.ClientRequest
	(*BallotNumber)(nil),          // 3: message.BallotNumber
	(*AcceptMessage)(nil),         // 4: message.AcceptMessage
	(*AcceptedMessage)(nil),       // 5: message.AcceptedMessage
	(*CommitMessage)(nil),         // 6: message.CommitMessage
	(*ReplyMessage)(nil),          // 7: message.ReplyMessage
	(*PrepareMessage)(nil),        // 8: message.PrepareMessage
	(*PromiseMessage)(nil),        // 9: message.PromiseMessage
	(*NewViewMessage)(nil),        // 10: message.NewViewMessage
	(*CheckpointMessage)(nil),     // 11: message.CheckpointMessage
	(*StateTranserRequest)(nil),   // 12: message.StateTranserRequest
	(*StateTransferResponse)(nil), // 13: message.StateTransferResponse
	(*TwoPCPrepareMessage)(nil),   // 14: message.TwoPCPrepareMessage
	(*TwoPCPreparedMessage)(nil),  // 15: message.TwoPCPreparedMessage
	(*TwoPCAbortMessage)(nil),     // 16: message.TwoPCAbortMessage
	(*TwoPCCommitMessage)(nil),    // 17: message.TwoPCCommitMessage
	(*TwoPCAckMessage)(nil),       // 18: message.TwoPCAckMessage
	(*PrintBalanceReq)(nil),       // 19: message.PrintBalanceReq
	nil,                           // 20: message.StateTransferResponse.StateEntry
	(*timestamppb.Timestamp)(nil), // 21: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 22: google.protobuf.Empty
}
var file_message_message_proto_depIdxs = []int32{
	21, // 0: message.ClientRequest.Timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: message.ClientRequest.Transaction:type_name -> message.Transaction
	3,  // 2: message.AcceptMessage.Ballot:type_name -> message.BallotNumber
	2,  // 3: message.AcceptMessage.Request:type_name -> message.ClientRequest
	0,  // 4: message.AcceptMessage.AcceptType:type_name -> message.AcceptType
	3,  // 5: message.AcceptedMessage.Ballot:type_name -> message.BallotNumber
	2,  // 6: message.AcceptedMessage.Request:type_name -> message.ClientRequest
	0,  // 7: message.AcceptedMessage.AcceptType:type_name -> message.AcceptType
	3,  // 8: message.CommitMessage.Ballot:type_name -> message.BallotNumber
	2,  // 9: message.CommitMessage.Request:type_name -> message.ClientRequest
	0,  // 10: message.CommitMessage.AcceptType:type_name -> message.AcceptType
	3,  // 11: message.ReplyMessage.Ballot:type_name -> message.BallotNumber
	21, // 12: message.ReplyMessage.ClientRequestTimestamp:type_name -> google.protobuf.Timestamp
	3,  // 13: message.PrepareMessage.Ballot:type_name -> message.BallotNumber
	3,  // 14: message.PromiseMessage.Ballot:type_name -> message.BallotNumber
	5,  // 15: message.PromiseMessage.AcceptLog:type_name -> message.AcceptedMessage
	3,  // 16: message.NewViewMessage.Ballot:type_name -> message.BallotNumber
	5,  // 17: message.NewViewMessage.AcceptLog:type_name -> message.AcceptedMessage
	20, // 18: message.StateTransferResponse.State:type_name -> message.StateTransferResponse.StateEntry
	2,  // 19: message.TwoPCPrepareMessage.Request:type_name -> message.ClientRequest
	2,  // 20: message.TwoPCPreparedMessage.Request:type_name -> message.ClientRequest
	2,  // 21: message.TwoPCAbortMessage.Request:type_name -> message.ClientRequest
	2,  // 22: message.TwoPCCommitMessage.Request:type_name -> message.ClientRequest
	2,  // 23: message.TwoPCAckMessage.Request:type_name -> message.ClientRequest
	2,  // 24: message.MessageService.SendRequestMessage:input_type -> message.ClientRequest
	4,  // 25: message.MessageService.HandleAccept:input_type -> message.AcceptMessage
	5,  // 26: message.MessageService.HandleAccepted:input_type -> message.AcceptedMessage
	6,  // 27: message.MessageService.HandleCommit:input_type -> message.CommitMessage
	8,  // 28: message.MessageService.HandlePrepare:input_type -> message.PrepareMessage
	9,  // 29: message.MessageService.HandlePromise:input_type -> message.PromiseMessage
	10, // 30: message.MessageService.HandleNewView:input_type -> message.NewViewMessage
	11, // 31: message.MessageService.HandleCheckpoint:input_type -> message.CheckpointMessage
	12, // 32: message.MessageService.MakeStateTransferRequest:input_type -> message.StateTranserRequest
	13, // 33: message.MessageService.HandleStateTransferResponse:input_type -> message.StateTransferResponse
	14, // 34: message.MessageService.HandleTwoPCPrepare:input_type -> message.TwoPCPrepareMessage
	15, // 35: message.MessageService.HandleTwoPCPrepared:input_type -> message.TwoPCPreparedMessage
	16, // 36: message.MessageService.HandleTwoPCAbortAsCoordinator:input_type -> message.TwoPCAbortMessage
	17, // 37: message.MessageService.HandleTwoPCCommit:input_type -> message.TwoPCCommitMessage
	18, // 38: message.MessageService.HandleTwoPCAck:input_type -> message.TwoPCAckMessage
	22, // 39: message.MessageService.PrintAcceptLog:input_type -> google.protobuf.Empty
	22, // 40: message.MessageService.FailNode:input_type -> google.protobuf.Empty
	22, // 41: message.MessageService.RecoverNode:input_type -> google.protobuf.Empty
	19, // 42: message.MessageService.PrintBalance:input_type -> message.PrintBalanceReq
	7,  // 43: message.ClientService.HandleReply:input_type -> message.ReplyMessage
	22, // 44: message.MessageService.SendRequestMessage:output_type -> google.protobuf.Empty
	22, // 45: message.MessageService.HandleAccept:output_type -> google.protobuf.Empty
	22, // 46: message.MessageService.HandleAccepted:output_type -> google.protobuf.Empty
	22, // 47: message.MessageService.HandleCommit:output_type -> google.protobuf.Empty
	22, // 48: message.MessageService.HandlePrepare:output_type -> google.protobuf.Empty
	22, // 49: message.MessageService.HandlePromise:output_type -> google.protobuf.Empty
	22, // 50: message.MessageService.HandleNewView:output_type -> google.protobuf.Empty
	22, // 51: message.MessageService.HandleCheckpoint:output_type -> google.protobuf.Empty
	22, // 52: message.MessageService.MakeStateTransferRequest:output_type -> google.protobuf.Empty
	22, // 53: message.MessageService.HandleStateTransferResponse:output_type -> google.protobuf.Empty
	22, // 54: message.MessageService.HandleTwoPCPrepare:output_type -> google.protobuf.Empty
	22, // 55: message.MessageService.HandleTwoPCPrepared:output_type -> google.protobuf.Empty
	22, // 56: message.MessageService.HandleTwoPCAbortAsCoordinator:output_type -> google.protobuf.Empty
	22, // 57: message.MessageService.HandleTwoPCCommit:output_type -> google.protobuf.Empty
	22, // 58: message.MessageService.HandleTwoPCAck:output_type -> google.protobuf.Empty
	22, // 59: message.MessageService.PrintAcceptLog:output_type -> google.protobuf.Empty
	22, // 60: message.MessageService.FailNode:output_type -> google.protobuf.Empty
	22, // 61: message.MessageService.RecoverNode:output_type -> google.protobuf.Empty
	22, // 62: message.MessageService.PrintBalance:output_type -> google.protobuf.Empty
	22, // 63: message.ClientService.HandleReply:output_type -> google.protobuf.Empty
	44, // [44:64] is the sub-list for method output_type
	24, // [24:44] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_message_message_proto_init() }
func file_message_message_proto_init() {
	if File_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_message_message_proto_goTypes,
		DependencyIndexes: file_message_message_proto_depIdxs,
		EnumInfos:         file_message_message_proto_enumTypes,
		MessageInfos:      file_message_message_proto_msgTypes,
	}.Build()
	File_message_message_proto = out.File
	file_message_message_proto_goTypes = nil
	file_message_message_proto_depIdxs = nil
}
