//
// Copyright (c) 2025 [Limark Dcunha]
// All rights reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: message/message.proto

// Use this command
// export PATH="$PATH:$(go env GOPATH)/bin"
// protoc --go_out=. --go_opt=paths=source_relative        --go-grpc_out=. --go-grpc_opt=paths=source_relative     message/message.proto

package message

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MessageService_SendRequestMessage_FullMethodName            = "/message.MessageService/SendRequestMessage"
	MessageService_HandleAccept_FullMethodName                  = "/message.MessageService/HandleAccept"
	MessageService_HandleAccepted_FullMethodName                = "/message.MessageService/HandleAccepted"
	MessageService_HandleCommit_FullMethodName                  = "/message.MessageService/HandleCommit"
	MessageService_HandlePrepare_FullMethodName                 = "/message.MessageService/HandlePrepare"
	MessageService_HandlePromise_FullMethodName                 = "/message.MessageService/HandlePromise"
	MessageService_HandleNewView_FullMethodName                 = "/message.MessageService/HandleNewView"
	MessageService_HandleCheckpoint_FullMethodName              = "/message.MessageService/HandleCheckpoint"
	MessageService_MakeStateTransferRequest_FullMethodName      = "/message.MessageService/MakeStateTransferRequest"
	MessageService_HandleStateTransferResponse_FullMethodName   = "/message.MessageService/HandleStateTransferResponse"
	MessageService_HandleTwoPCPrepare_FullMethodName            = "/message.MessageService/HandleTwoPCPrepare"
	MessageService_HandleTwoPCPrepared_FullMethodName           = "/message.MessageService/HandleTwoPCPrepared"
	MessageService_HandleTwoPCAbortAsCoordinator_FullMethodName = "/message.MessageService/HandleTwoPCAbortAsCoordinator"
	MessageService_HandleTwoPCAbortAsParticipant_FullMethodName = "/message.MessageService/HandleTwoPCAbortAsParticipant"
	MessageService_HandleTwoPCCommit_FullMethodName             = "/message.MessageService/HandleTwoPCCommit"
	MessageService_HandleTwoPCAck_FullMethodName                = "/message.MessageService/HandleTwoPCAck"
	MessageService_PrintAcceptLog_FullMethodName                = "/message.MessageService/PrintAcceptLog"
	MessageService_FailNode_FullMethodName                      = "/message.MessageService/FailNode"
	MessageService_RecoverNode_FullMethodName                   = "/message.MessageService/RecoverNode"
	MessageService_PrintBalance_FullMethodName                  = "/message.MessageService/PrintBalance"
	MessageService_ApplyShardMap_FullMethodName                 = "/message.MessageService/ApplyShardMap"
	MessageService_MoveDatapoint_FullMethodName                 = "/message.MessageService/MoveDatapoint"
	MessageService_DeleteDatapoint_FullMethodName               = "/message.MessageService/DeleteDatapoint"
	MessageService_GetBalance_FullMethodName                    = "/message.MessageService/GetBalance"
)

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	SendRequestMessage(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleAccept(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleAccepted(ctx context.Context, in *AcceptedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleCommit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandlePrepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandlePromise(ctx context.Context, in *PromiseMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleNewView(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleCheckpoint(ctx context.Context, in *CheckpointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MakeStateTransferRequest(ctx context.Context, in *StateTranserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleStateTransferResponse(ctx context.Context, in *StateTransferResponse, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCPrepare(ctx context.Context, in *TwoPCPrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCPrepared(ctx context.Context, in *TwoPCPreparedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCAbortAsCoordinator(ctx context.Context, in *TwoPCAbortMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCAbortAsParticipant(ctx context.Context, in *TwoPCAbortMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCCommit(ctx context.Context, in *TwoPCCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	HandleTwoPCAck(ctx context.Context, in *TwoPCAckMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Project helpers
	PrintAcceptLog(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	FailNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RecoverNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PrintBalance(ctx context.Context, in *PrintBalanceReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ApplyShardMap(ctx context.Context, in *ApplyShardMapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MoveDatapoint(ctx context.Context, in *MoveDatapointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteDatapoint(ctx context.Context, in *DeleteDatapointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
}

type messageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageServiceClient(cc grpc.ClientConnInterface) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) SendRequestMessage(ctx context.Context, in *ClientRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_SendRequestMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleAccept(ctx context.Context, in *AcceptMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleAccept_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleAccepted(ctx context.Context, in *AcceptedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleAccepted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleCommit(ctx context.Context, in *CommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandlePrepare(ctx context.Context, in *PrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandlePrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandlePromise(ctx context.Context, in *PromiseMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandlePromise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleNewView(ctx context.Context, in *NewViewMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleNewView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleCheckpoint(ctx context.Context, in *CheckpointMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MakeStateTransferRequest(ctx context.Context, in *StateTranserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_MakeStateTransferRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleStateTransferResponse(ctx context.Context, in *StateTransferResponse, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleStateTransferResponse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCPrepare(ctx context.Context, in *TwoPCPrepareMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCPrepare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCPrepared(ctx context.Context, in *TwoPCPreparedMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCPrepared_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCAbortAsCoordinator(ctx context.Context, in *TwoPCAbortMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCAbortAsCoordinator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCAbortAsParticipant(ctx context.Context, in *TwoPCAbortMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCAbortAsParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCCommit(ctx context.Context, in *TwoPCCommitMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) HandleTwoPCAck(ctx context.Context, in *TwoPCAckMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_HandleTwoPCAck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PrintAcceptLog(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_PrintAcceptLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) FailNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_FailNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) RecoverNode(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_RecoverNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) PrintBalance(ctx context.Context, in *PrintBalanceReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_PrintBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) ApplyShardMap(ctx context.Context, in *ApplyShardMapRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_ApplyShardMap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) MoveDatapoint(ctx context.Context, in *MoveDatapointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_MoveDatapoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) DeleteDatapoint(ctx context.Context, in *DeleteDatapointRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MessageService_DeleteDatapoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageServiceClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, MessageService_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility.
type MessageServiceServer interface {
	SendRequestMessage(context.Context, *ClientRequest) (*emptypb.Empty, error)
	HandleAccept(context.Context, *AcceptMessage) (*emptypb.Empty, error)
	HandleAccepted(context.Context, *AcceptedMessage) (*emptypb.Empty, error)
	HandleCommit(context.Context, *CommitMessage) (*emptypb.Empty, error)
	HandlePrepare(context.Context, *PrepareMessage) (*emptypb.Empty, error)
	HandlePromise(context.Context, *PromiseMessage) (*emptypb.Empty, error)
	HandleNewView(context.Context, *NewViewMessage) (*emptypb.Empty, error)
	HandleCheckpoint(context.Context, *CheckpointMessage) (*emptypb.Empty, error)
	MakeStateTransferRequest(context.Context, *StateTranserRequest) (*emptypb.Empty, error)
	HandleStateTransferResponse(context.Context, *StateTransferResponse) (*emptypb.Empty, error)
	HandleTwoPCPrepare(context.Context, *TwoPCPrepareMessage) (*emptypb.Empty, error)
	HandleTwoPCPrepared(context.Context, *TwoPCPreparedMessage) (*emptypb.Empty, error)
	HandleTwoPCAbortAsCoordinator(context.Context, *TwoPCAbortMessage) (*emptypb.Empty, error)
	HandleTwoPCAbortAsParticipant(context.Context, *TwoPCAbortMessage) (*emptypb.Empty, error)
	HandleTwoPCCommit(context.Context, *TwoPCCommitMessage) (*emptypb.Empty, error)
	HandleTwoPCAck(context.Context, *TwoPCAckMessage) (*emptypb.Empty, error)
	// Project helpers
	PrintAcceptLog(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	FailNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	RecoverNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	PrintBalance(context.Context, *PrintBalanceReq) (*emptypb.Empty, error)
	ApplyShardMap(context.Context, *ApplyShardMapRequest) (*emptypb.Empty, error)
	MoveDatapoint(context.Context, *MoveDatapointRequest) (*emptypb.Empty, error)
	DeleteDatapoint(context.Context, *DeleteDatapointRequest) (*emptypb.Empty, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMessageServiceServer struct{}

func (UnimplementedMessageServiceServer) SendRequestMessage(context.Context, *ClientRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendRequestMessage not implemented")
}
func (UnimplementedMessageServiceServer) HandleAccept(context.Context, *AcceptMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAccept not implemented")
}
func (UnimplementedMessageServiceServer) HandleAccepted(context.Context, *AcceptedMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleAccepted not implemented")
}
func (UnimplementedMessageServiceServer) HandleCommit(context.Context, *CommitMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedMessageServiceServer) HandlePrepare(context.Context, *PrepareMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePrepare not implemented")
}
func (UnimplementedMessageServiceServer) HandlePromise(context.Context, *PromiseMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandlePromise not implemented")
}
func (UnimplementedMessageServiceServer) HandleNewView(context.Context, *NewViewMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleNewView not implemented")
}
func (UnimplementedMessageServiceServer) HandleCheckpoint(context.Context, *CheckpointMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleCheckpoint not implemented")
}
func (UnimplementedMessageServiceServer) MakeStateTransferRequest(context.Context, *StateTranserRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeStateTransferRequest not implemented")
}
func (UnimplementedMessageServiceServer) HandleStateTransferResponse(context.Context, *StateTransferResponse) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleStateTransferResponse not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCPrepare(context.Context, *TwoPCPrepareMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCPrepare not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCPrepared(context.Context, *TwoPCPreparedMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCPrepared not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCAbortAsCoordinator(context.Context, *TwoPCAbortMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCAbortAsCoordinator not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCAbortAsParticipant(context.Context, *TwoPCAbortMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCAbortAsParticipant not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCCommit(context.Context, *TwoPCCommitMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCCommit not implemented")
}
func (UnimplementedMessageServiceServer) HandleTwoPCAck(context.Context, *TwoPCAckMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleTwoPCAck not implemented")
}
func (UnimplementedMessageServiceServer) PrintAcceptLog(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintAcceptLog not implemented")
}
func (UnimplementedMessageServiceServer) FailNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FailNode not implemented")
}
func (UnimplementedMessageServiceServer) RecoverNode(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecoverNode not implemented")
}
func (UnimplementedMessageServiceServer) PrintBalance(context.Context, *PrintBalanceReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrintBalance not implemented")
}
func (UnimplementedMessageServiceServer) ApplyShardMap(context.Context, *ApplyShardMapRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyShardMap not implemented")
}
func (UnimplementedMessageServiceServer) MoveDatapoint(context.Context, *MoveDatapointRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MoveDatapoint not implemented")
}
func (UnimplementedMessageServiceServer) DeleteDatapoint(context.Context, *DeleteDatapointRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDatapoint not implemented")
}
func (UnimplementedMessageServiceServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}
func (UnimplementedMessageServiceServer) testEmbeddedByValue()                        {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc.ServiceRegistrar, srv MessageServiceServer) {
	// If the following call pancis, it indicates UnimplementedMessageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_SendRequestMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).SendRequestMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_SendRequestMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).SendRequestMessage(ctx, req.(*ClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleAccept_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleAccept(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleAccept_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleAccept(ctx, req.(*AcceptMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleAccepted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleAccepted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleAccepted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleAccepted(ctx, req.(*AcceptedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleCommit(ctx, req.(*CommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandlePrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandlePrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandlePrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandlePrepare(ctx, req.(*PrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandlePromise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromiseMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandlePromise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandlePromise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandlePromise(ctx, req.(*PromiseMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleNewView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewViewMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleNewView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleNewView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleNewView(ctx, req.(*NewViewMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckpointMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleCheckpoint(ctx, req.(*CheckpointMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MakeStateTransferRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateTranserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MakeStateTransferRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MakeStateTransferRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MakeStateTransferRequest(ctx, req.(*StateTranserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleStateTransferResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateTransferResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleStateTransferResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleStateTransferResponse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleStateTransferResponse(ctx, req.(*StateTransferResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCPrepare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCPrepareMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCPrepare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCPrepare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCPrepare(ctx, req.(*TwoPCPrepareMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCPrepared_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCPreparedMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCPrepared(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCPrepared_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCPrepared(ctx, req.(*TwoPCPreparedMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCAbortAsCoordinator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCAbortMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCAbortAsCoordinator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCAbortAsCoordinator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCAbortAsCoordinator(ctx, req.(*TwoPCAbortMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCAbortAsParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCAbortMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCAbortAsParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCAbortAsParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCAbortAsParticipant(ctx, req.(*TwoPCAbortMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCCommitMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCCommit(ctx, req.(*TwoPCCommitMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_HandleTwoPCAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TwoPCAckMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).HandleTwoPCAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_HandleTwoPCAck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).HandleTwoPCAck(ctx, req.(*TwoPCAckMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PrintAcceptLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PrintAcceptLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PrintAcceptLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PrintAcceptLog(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_FailNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).FailNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_FailNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).FailNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_RecoverNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).RecoverNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_RecoverNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).RecoverNode(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_PrintBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrintBalanceReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).PrintBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_PrintBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).PrintBalance(ctx, req.(*PrintBalanceReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_ApplyShardMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyShardMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).ApplyShardMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_ApplyShardMap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).ApplyShardMap(ctx, req.(*ApplyShardMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_MoveDatapoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MoveDatapointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).MoveDatapoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_MoveDatapoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).MoveDatapoint(ctx, req.(*MoveDatapointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_DeleteDatapoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatapointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).DeleteDatapoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_DeleteDatapoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).DeleteDatapoint(ctx, req.(*DeleteDatapointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MessageService_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServiceServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MessageService_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServiceServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendRequestMessage",
			Handler:    _MessageService_SendRequestMessage_Handler,
		},
		{
			MethodName: "HandleAccept",
			Handler:    _MessageService_HandleAccept_Handler,
		},
		{
			MethodName: "HandleAccepted",
			Handler:    _MessageService_HandleAccepted_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _MessageService_HandleCommit_Handler,
		},
		{
			MethodName: "HandlePrepare",
			Handler:    _MessageService_HandlePrepare_Handler,
		},
		{
			MethodName: "HandlePromise",
			Handler:    _MessageService_HandlePromise_Handler,
		},
		{
			MethodName: "HandleNewView",
			Handler:    _MessageService_HandleNewView_Handler,
		},
		{
			MethodName: "HandleCheckpoint",
			Handler:    _MessageService_HandleCheckpoint_Handler,
		},
		{
			MethodName: "MakeStateTransferRequest",
			Handler:    _MessageService_MakeStateTransferRequest_Handler,
		},
		{
			MethodName: "HandleStateTransferResponse",
			Handler:    _MessageService_HandleStateTransferResponse_Handler,
		},
		{
			MethodName: "HandleTwoPCPrepare",
			Handler:    _MessageService_HandleTwoPCPrepare_Handler,
		},
		{
			MethodName: "HandleTwoPCPrepared",
			Handler:    _MessageService_HandleTwoPCPrepared_Handler,
		},
		{
			MethodName: "HandleTwoPCAbortAsCoordinator",
			Handler:    _MessageService_HandleTwoPCAbortAsCoordinator_Handler,
		},
		{
			MethodName: "HandleTwoPCAbortAsParticipant",
			Handler:    _MessageService_HandleTwoPCAbortAsParticipant_Handler,
		},
		{
			MethodName: "HandleTwoPCCommit",
			Handler:    _MessageService_HandleTwoPCCommit_Handler,
		},
		{
			MethodName: "HandleTwoPCAck",
			Handler:    _MessageService_HandleTwoPCAck_Handler,
		},
		{
			MethodName: "PrintAcceptLog",
			Handler:    _MessageService_PrintAcceptLog_Handler,
		},
		{
			MethodName: "FailNode",
			Handler:    _MessageService_FailNode_Handler,
		},
		{
			MethodName: "RecoverNode",
			Handler:    _MessageService_RecoverNode_Handler,
		},
		{
			MethodName: "PrintBalance",
			Handler:    _MessageService_PrintBalance_Handler,
		},
		{
			MethodName: "ApplyShardMap",
			Handler:    _MessageService_ApplyShardMap_Handler,
		},
		{
			MethodName: "MoveDatapoint",
			Handler:    _MessageService_MoveDatapoint_Handler,
		},
		{
			MethodName: "DeleteDatapoint",
			Handler:    _MessageService_DeleteDatapoint_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _MessageService_GetBalance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/message.proto",
}

const (
	ClientService_HandleReply_FullMethodName = "/message.ClientService/HandleReply"
)

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClientServiceClient interface {
	HandleReply(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) HandleReply(ctx context.Context, in *ReplyMessage, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, ClientService_HandleReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
// All implementations must embed UnimplementedClientServiceServer
// for forward compatibility.
type ClientServiceServer interface {
	HandleReply(context.Context, *ReplyMessage) (*emptypb.Empty, error)
	mustEmbedUnimplementedClientServiceServer()
}

// UnimplementedClientServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClientServiceServer struct{}

func (UnimplementedClientServiceServer) HandleReply(context.Context, *ReplyMessage) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleReply not implemented")
}
func (UnimplementedClientServiceServer) mustEmbedUnimplementedClientServiceServer() {}
func (UnimplementedClientServiceServer) testEmbeddedByValue()                       {}

// UnsafeClientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClientServiceServer will
// result in compilation errors.
type UnsafeClientServiceServer interface {
	mustEmbedUnimplementedClientServiceServer()
}

func RegisterClientServiceServer(s grpc.ServiceRegistrar, srv ClientServiceServer) {
	// If the following call pancis, it indicates UnimplementedClientServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClientService_ServiceDesc, srv)
}

func _ClientService_HandleReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).HandleReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClientService_HandleReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).HandleReply(ctx, req.(*ReplyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// ClientService_ServiceDesc is the grpc.ServiceDesc for ClientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleReply",
			Handler:    _ClientService_HandleReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message/message.proto",
}
