//
// Copyright (c) 2025 [Limark Dcunha]
// All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: message/message.proto

// Use this command
// export PATH="$PATH:$(go env GOPATH)/bin"
// protoc --go_out=. --go_opt=paths=source_relative        --go-grpc_out=. --go-grpc_opt=paths=source_relative     message/message.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        string                 `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Receiver      string                 `protobuf:"bytes,2,opt,name=Receiver,proto3" json:"Receiver,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_message_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Transaction) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *Transaction) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type ClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,2,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	ClientId      int32                  `protobuf:"varint,3,opt,name=ClientId,proto3" json:"ClientId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_message_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{1}
}

func (x *ClientRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ClientRequest) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *ClientRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

type BallotNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	RounderNumber int32                  `protobuf:"varint,2,opt,name=RounderNumber,proto3" json:"RounderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BallotNumber) Reset() {
	*x = BallotNumber{}
	mi := &file_message_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BallotNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallotNumber) ProtoMessage() {}

func (x *BallotNumber) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallotNumber.ProtoReflect.Descriptor instead.
func (*BallotNumber) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{2}
}

func (x *BallotNumber) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *BallotNumber) GetRounderNumber() int32 {
	if x != nil {
		return x.RounderNumber
	}
	return 0
}

type AcceptMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptMessage) Reset() {
	*x = AcceptMessage{}
	mi := &file_message_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptMessage) ProtoMessage() {}

func (x *AcceptMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptMessage.ProtoReflect.Descriptor instead.
func (*AcceptMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type AcceptedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	NodeId        int32                  `protobuf:"varint,4,opt,name=NodeId,proto3" json:"NodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptedMessage) Reset() {
	*x = AcceptedMessage{}
	mi := &file_message_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptedMessage) ProtoMessage() {}

func (x *AcceptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptedMessage.ProtoReflect.Descriptor instead.
func (*AcceptedMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptedMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *AcceptedMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *AcceptedMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *AcceptedMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type CommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ballot        *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,2,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	Request       *ClientRequest         `protobuf:"bytes,3,opt,name=Request,proto3" json:"Request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitMessage) Reset() {
	*x = CommitMessage{}
	mi := &file_message_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitMessage) ProtoMessage() {}

func (x *CommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitMessage.ProtoReflect.Descriptor instead.
func (*CommitMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{5}
}

func (x *CommitMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *CommitMessage) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *CommitMessage) GetRequest() *ClientRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type ReplyMessage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Ballot                 *BallotNumber          `protobuf:"bytes,1,opt,name=Ballot,proto3" json:"Ballot,omitempty"`
	ClientRequestTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=ClientRequestTimestamp,proto3" json:"ClientRequestTimestamp,omitempty"`
	Status                 string                 `protobuf:"bytes,3,opt,name=Status,proto3" json:"Status,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_message_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_message_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_message_message_proto_rawDescGZIP(), []int{6}
}

func (x *ReplyMessage) GetBallot() *BallotNumber {
	if x != nil {
		return x.Ballot
	}
	return nil
}

func (x *ReplyMessage) GetClientRequestTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientRequestTimestamp
	}
	return nil
}

func (x *ReplyMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_message_message_proto protoreflect.FileDescriptor

const file_message_message_proto_rawDesc = "" +
	"\n" +
	"\x15message/message.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\vTransaction\x12\x16\n" +
	"\x06Sender\x18\x01 \x01(\tR\x06Sender\x12\x1a\n" +
	"\bReceiver\x18\x02 \x01(\tR\bReceiver\x12\x16\n" +
	"\x06Amount\x18\x03 \x01(\x05R\x06Amount\"\x9d\x01\n" +
	"\rClientRequest\x128\n" +
	"\tTimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tTimestamp\x126\n" +
	"\vTransaction\x18\x02 \x01(\v2\x14.message.TransactionR\vTransaction\x12\x1a\n" +
	"\bClientId\x18\x03 \x01(\x05R\bClientId\"L\n" +
	"\fBallotNumber\x12\x16\n" +
	"\x06NodeId\x18\x01 \x01(\x05R\x06NodeId\x12$\n" +
	"\rRounderNumber\x18\x02 \x01(\x05R\rRounderNumber\"\x92\x01\n" +
	"\rAcceptMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\"\xac\x01\n" +
	"\x0fAcceptedMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\x12\x16\n" +
	"\x06NodeId\x18\x04 \x01(\x05R\x06NodeId\"\x92\x01\n" +
	"\rCommitMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12 \n" +
	"\vSequenceNum\x18\x02 \x01(\x05R\vSequenceNum\x120\n" +
	"\aRequest\x18\x03 \x01(\v2\x16.message.ClientRequestR\aRequest\"\xa9\x01\n" +
	"\fReplyMessage\x12-\n" +
	"\x06Ballot\x18\x01 \x01(\v2\x15.message.BallotNumberR\x06Ballot\x12R\n" +
	"\x16ClientRequestTimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x16ClientRequestTimestamp\x12\x16\n" +
	"\x06Status\x18\x03 \x01(\tR\x06Status2\x9c\x02\n" +
	"\x0eMessageService\x12D\n" +
	"\x12SendRequestMessage\x12\x16.message.ClientRequest\x1a\x16.google.protobuf.Empty\x12>\n" +
	"\fHandleAccept\x12\x16.message.AcceptMessage\x1a\x16.google.protobuf.Empty\x12B\n" +
	"\x0eHandleAccepted\x12\x18.message.AcceptedMessage\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\fHandleCommit\x12\x18.message.AcceptedMessage\x1a\x16.google.protobuf.Empty2M\n" +
	"\rClientService\x12<\n" +
	"\vHandleReply\x12\x15.message.ReplyMessage\x1a\x16.google.protobuf.EmptyB\x1fZ\x1dtransaction-processor/messageb\x06proto3"

var (
	file_message_message_proto_rawDescOnce sync.Once
	file_message_message_proto_rawDescData []byte
)

func file_message_message_proto_rawDescGZIP() []byte {
	file_message_message_proto_rawDescOnce.Do(func() {
		file_message_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)))
	})
	return file_message_message_proto_rawDescData
}

var file_message_message_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_message_message_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: message.Transaction
	(*ClientRequest)(nil),         // 1: message.ClientRequest
	(*BallotNumber)(nil),          // 2: message.BallotNumber
	(*AcceptMessage)(nil),         // 3: message.AcceptMessage
	(*AcceptedMessage)(nil),       // 4: message.AcceptedMessage
	(*CommitMessage)(nil),         // 5: message.CommitMessage
	(*ReplyMessage)(nil),          // 6: message.ReplyMessage
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 8: google.protobuf.Empty
}
var file_message_message_proto_depIdxs = []int32{
	7,  // 0: message.ClientRequest.Timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: message.ClientRequest.Transaction:type_name -> message.Transaction
	2,  // 2: message.AcceptMessage.Ballot:type_name -> message.BallotNumber
	1,  // 3: message.AcceptMessage.Request:type_name -> message.ClientRequest
	2,  // 4: message.AcceptedMessage.Ballot:type_name -> message.BallotNumber
	1,  // 5: message.AcceptedMessage.Request:type_name -> message.ClientRequest
	2,  // 6: message.CommitMessage.Ballot:type_name -> message.BallotNumber
	1,  // 7: message.CommitMessage.Request:type_name -> message.ClientRequest
	2,  // 8: message.ReplyMessage.Ballot:type_name -> message.BallotNumber
	7,  // 9: message.ReplyMessage.ClientRequestTimestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: message.MessageService.SendRequestMessage:input_type -> message.ClientRequest
	3,  // 11: message.MessageService.HandleAccept:input_type -> message.AcceptMessage
	4,  // 12: message.MessageService.HandleAccepted:input_type -> message.AcceptedMessage
	4,  // 13: message.MessageService.HandleCommit:input_type -> message.AcceptedMessage
	6,  // 14: message.ClientService.HandleReply:input_type -> message.ReplyMessage
	8,  // 15: message.MessageService.SendRequestMessage:output_type -> google.protobuf.Empty
	8,  // 16: message.MessageService.HandleAccept:output_type -> google.protobuf.Empty
	8,  // 17: message.MessageService.HandleAccepted:output_type -> google.protobuf.Empty
	8,  // 18: message.MessageService.HandleCommit:output_type -> google.protobuf.Empty
	8,  // 19: message.ClientService.HandleReply:output_type -> google.protobuf.Empty
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_message_message_proto_init() }
func file_message_message_proto_init() {
	if File_message_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_message_proto_rawDesc), len(file_message_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_message_message_proto_goTypes,
		DependencyIndexes: file_message_message_proto_depIdxs,
		MessageInfos:      file_message_message_proto_msgTypes,
	}.Build()
	File_message_message_proto = out.File
	file_message_message_proto_goTypes = nil
	file_message_message_proto_depIdxs = nil
}
